# Generated by Django 5.1.3 on 2024-11-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registration_date',
            new_name='registered_at',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='practice',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
