# Generated by Django 5.1.3 on 2024-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_registration_date_registration_registered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
