# Generated by Django 5.1.3 on 2024-11-09 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_practice_max_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'practice')},
        ),
    ]
